scan_to_scan_filter_chain:
  ros__parameters:
    # Filter chain for removing robot self-detections
    filter_chain:
      - name: range_filter
        type: laser_filters/LaserScanRangeFilter
        params:
          use_message_range_limits: false
          lower_threshold: 0.30
          upper_threshold: 3.5
          lower_replacement_value: .nan
          upper_replacement_value: .nan
